name: 'kindlegen'
description: 'Run kindlegen on epub files'
author: 'dariusf'
inputs:
  path:
    description: 'path of epub file to convert'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
